version: "3.9"

services:
  resource-db:
    image: postgres:17-alpine
    container_name: resource-db
    environment:
      POSTGRES_DB: resource_service
      POSTGRES_USER: resource_user
      POSTGRES_PASSWORD: resource_pass
    ports:
      - "5433:5432"
    networks:
      - microservices-net

  song-db:
    image: postgres:17-alpine
    container_name: song-db
    environment:
      POSTGRES_DB: song_service
      POSTGRES_USER: song_user
      POSTGRES_PASSWORD: song_pass
    ports:
      - "5434:5432"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
