version: "3.9"

services:
  resource-db:
    image: postgres:17-alpine
    container_name: resource-db
    environment:
      POSTGRES_DB: ${RESOURCE_DB}
      POSTGRES_USER: ${RESOURCE_DB_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
    ports:
      - "${RESOURCE_DB_HOST_PORT}:5432"
    volumes:
      - ./init-scripts/resource-db:/docker-entrypoint-initdb.d
    networks:
      - microservices-net

  song-db:
    image: postgres:17-alpine
    container_name: song-db
    environment:
      POSTGRES_DB: ${SONG_DB}
      POSTGRES_USER: ${SONG_DB_USER}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
    ports:
      - "${SONG_DB_HOST_PORT}:5432"
    volumes:
      - ./init-scripts/song-db:/docker-entrypoint-initdb.d
    networks:
      - microservices-net

  resource-service:
    build:
      context: ./resource-service
      dockerfile: Dockerfile
    container_name: resource-service
    depends_on:
      - resource-db
      - song-db
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_DB_PASSWORD}
      SERVER_PORT: ${RESOURCE_SERVER_PORT}
      SONG_SERVICE_BASE_URL: ${SONG_SERVICE_BASE_URL}
    ports:
      - "${RESOURCE_SERVER_PORT}:${RESOURCE_SERVER_PORT}"
    networks:
      - microservices-net

  song-service:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    container_name: song-service
    depends_on:
      - song-db
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SONG_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SONG_DB_PASSWORD}
      SERVER_PORT: ${SONG_SERVER_PORT}
    ports:
      - "${SONG_SERVER_PORT}:${SONG_SERVER_PORT}"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
