spring:
  application:
    name: song-service

  datasource:
    url: jdbc:postgresql://localhost:5434/song_service
    username: song_user
    password: song_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: postgresql

server:
  port: 8072
