spring:
  application:
    name: song-service

  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/song_service}"
    username: "${SPRING_DATASOURCE_USERNAME:song_user}"
    password: "${SPRING_DATASOURCE_PASSWORD:song_pass}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: postgresql

server:
  port: "${SERVER_PORT:8072}"