spring:
  application:
    name: resource-service

  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/resource_service}"
    username: "${SPRING_DATASOURCE_USERNAME:resource_user}"
    password: "${SPRING_DATASOURCE_PASSWORD:resource_pass}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: postgresql

server:
  port: "${SERVER_PORT:8071}"

song-service:
  base-url: "${SONG_SERVICE_BASE_URL:http://localhost:8072}"